# mirror link
mirror_link=https://mirrors.oneinstack.com

# set the default timezone
timezone=Asia/Shanghai

# Nginx worker user/group
run_user=www
run_group=www

# install paths
nginx_install_dir=/usr/local/nginx
openssl_install_dir=/usr/local/openssl

# custom Nginx configure module options
nginx_modules_options=''

# web directory
wwwroot_dir=/data/wwwroot

# Nginx log directory
wwwlogs_dir=/data/wwwlogs
